name: gmail_main_view
description: "gmail main view"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/gmail_main_view

version: 1.0.4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  hive:
  isar_flutter_libs: ^4.0.0-dev.14
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  path_provider:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  hive_module: ^1.0.5
  june_view:  #@add
  june_view_more:  #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/gmail_main_view/
  uses-material-design: true